HOST = '0.0.0.0'
PORT = 9098
TEST_TIMEOUT_S = 60
RUN_TIMEOUT_S = 60
ACCESS_TIMEOUT_S = 5

REPORT_SERVER_HOST = '<IP ADDRESS OF TARGET REPORT SERVER>'
REPORT_SERVER_PORT = 80
REPORT_SERVER_PATH = 'contest/jury/judge/automated/'

TEST_FILES_PATH = '<ADDRESS IN WHICH TESTS ARE LOCATED>'
TEST_HANDLER_MODULE = "<MODULE NAME>"

MAX_MEMORY_CONTESTANT = 50

PROJECT_ROOT = "/home/soroushvt/code/webelopers/judge/"